### PR TITLE
Add support url parameters

### PR DESCRIPTION
**Pull request by haydnhkim**
router5 uses the path-parser.
It can use [:param syntax](https://router5.js.org/guides/path-syntax#defining-parameters). so, link interceptor should be able to recognize parameters in url and pass them as params arguments in the navigate function.
I combined the query params with the url params ​​recognized by toRouteState.

This has been tested in router5 v5 and v6.
Thanks!

### CODE REVIEW

**Comment by jas-chen** [comment]
hi @haydnhkim,

`Object.assign` is not supported in IE, could you use another way to do this?

**Comment by haydnhkim** [comment]
I changed it to a simple merge function.
I think `Object.keys` will not be a problem since it is already in use on router5.

**Comment by haydnhkim** [comment]
@jas-chen I changed it to a simple merge function.
I think `Object.keys` will not be a problem since it is already in use on router5.

**Comment by haydnhkim** [comment]
@jas-chen I changed it to a simple merge function.
I think `Object.keys` will not be a problem since it is already in use on router5.

**Comment by jas-chen** [comment]
@haydnhkim sorry for the late update, i've published v3.1.0, please give it a test, thanks!

**Comment by haydnhkim** [comment]
It works well. Thank you!

**Pull request merged**
